### ISSUE TITLE
Installation barks 

### ISSUE THREAD

**Issue by lipnikov** [laristra/flecsale#69]
Command suggested in README fails:

git clone --recursive -b feature/flegion git@github.com:laristra/flecsale.git 
Cloning into 'flecsale'...
Permission denied (publickey).
fatal: Could not read from remote repository.

A new command 
git clone --recursive -b feature/flegion https://github.com/laristra/flecsale.git FleCSALE

fails after a while with the following  message:

fatal: reference is not a tree: a6d079862a19511228d076b4939e69a8dff4e6ac
Unable to checkout 'a6d079862a19511228d076b4939e69a8dff4e6ac' in submodule path 'flecsi/cinch'

**Comment by charest** [comment]
That branch is almost a year old...  please use master

**Comment by lipnikov** [comment]
Which branch are u talking about? I cannot clone the repository. Please provide correct clone instruction.

**Comment by charest** [comment]
Please make sure your ssh keys are setup correctly.

https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by jlippuner** [comment]
The README says to clone the repo as follows:
`git clone --recursive https://github.com/laristra/flecsale.git`

This will give you the master branch and should work even without SSH keys set up.

**Comment by lipnikov** [comment]
Thanks. I see that  "-b feature/flegion"  is no longer recommended. It works  now
