### ISSUE TITLE
Different location of TPLs leads to compilation error

### ISSUE THREAD

**Issue by lipnikov** [laristra/flecsale#71]
If ParMetis and Exodus are located in two different directories, the code fails to compile burton/burton_specialization_init.cc. Error message is 

FleCSALE/flecsi/flecsi/coloring/parmetis_colorer.h:26:10: fatal error: parmetis.h: No such file or directory

I have correct PARMETIS_DIR, PARMETIS_INCLUDE_DIR, PARMETIS_LIBRARY in CMakeCache.txt;
however, compiler uses only one include directory which Exodus.

**Comment by junghans** [comment]
Patches welcome!

**Comment by charest** [comment]
I tried to reproduce this but was unable to.  Closing unless further evidence.
